
@hostname = http://localhost:3000
GET {{hostname}}/api/public/auth

###

POST {{hostname}}/api/public/auth/register
content-type: application/json

{
	"lastname": "a",
	"firstname": "a",
	"email": "john@doe.io",
	"password": "changeme"
}

###

POST http://localhost:3000/auth/login/
content-type: application/json

{
	"email": "john@doe.io",
 	"password": "changeme"
 }

###

GET http://localhost:3000/profile