
@hostname = http://localhost:3000
GET {{hostname}}/api/public/auth

###

POST {{hostname}}/api/public/auth/register
content-type: application/json

{
	"lastname": "a",
	"firstname": "a",
	"email": "a@a.a",
	"password": "a"
}